/**
 * instanthpi/pdf/generate.cjs
 *
 * Generate a new fillable PDF from scratch using pdf-lib. This ships one
 * example template -- a generic referral letter with an AcroForm (so it can
 * later be filled again programmatically via pdf-lib or via
 * instanthpi/pdf/fill.py, or filled by hand in any PDF reader).
 *
 * No real signature image is embedded. If the physician has configured
 * SIGNATURE_IMAGE_PATH (see .env.example) and the file exists, it is drawn
 * onto the signature line; otherwise a blank line is left for a manual
 * signature. Signing therefore stays an explicit, physician-controlled step
 * either way.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');

const PAGE_WIDTH = 612; // US Letter, points
const PAGE_HEIGHT = 792;

/**
 * @param {string} outputPath - where to write the generated PDF.
 * @param {object} [values] - optional default field values.
 * @param {string} [values.fromPhysicianName]
 * @param {string} [values.fromClinicName]
 * @param {string} [values.patientName]
 * @param {string} [values.dateOfBirth] - free text here (this template's
 *   date field is a plain text field, not a comb field; see pdf/fill.py for
 *   comb-field date handling when filling an *existing* form).
 * @param {string} [values.referredToProviderOrClinic]
 * @param {string} [values.reasonForReferral]
 * @param {string} [values.clinicalSummary]
 * @param {string} [values.date]
 * @param {string} [signatureImagePath] - defaults to
 *   process.env.SIGNATURE_IMAGE_PATH. Never a path checked into this repo.
 */
async function generateReferralLetter(outputPath, values = {}, signatureImagePath) {
  const doc = await PDFDocument.create();
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const boldFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const form = doc.getForm();

  let y = PAGE_HEIGHT - 60;
  const left = 54;

  page.drawText('Medical Referral Letter', {
    x: left,
    y,
    size: 18,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= 30;

  page.drawText(
    'Generated by instanthpi (freeeducationhealth) -- self-hosted, no shared infrastructure.',
    { x: left, y, size: 8, font, color: rgb(0.4, 0.4, 0.4) },
  );
  y -= 30;

  function addLabeledField(label, fieldName, { height = 18, value = '', multiline = false } = {}) {
    page.drawText(label, { x: left, y, size: 10, font: boldFont });
    y -= 4;
    const fieldHeight = multiline ? height * 3 : height;
    const field = multiline
      ? form.createTextField(fieldName)
      : form.createTextField(fieldName);
    if (multiline) field.enableMultiline();
    field.setText(value || '');
    field.addToPage(page, {
      x: left,
      y: y - fieldHeight,
      width: PAGE_WIDTH - left * 2,
      height: fieldHeight,
      borderWidth: 1,
      borderColor: rgb(0.7, 0.7, 0.7),
    });
    y -= fieldHeight + 14;
  }

  addLabeledField('Referring physician', 'fromPhysicianName', { value: values.fromPhysicianName });
  addLabeledField('Referring clinic', 'fromClinicName', { value: values.fromClinicName });
  addLabeledField('Patient name', 'patientName', { value: values.patientName });
  addLabeledField('Date of birth', 'dateOfBirth', { value: values.dateOfBirth });
  addLabeledField('Referred to', 'referredToProviderOrClinic', {
    value: values.referredToProviderOrClinic,
  });
  addLabeledField('Reason for referral', 'reasonForReferral', {
    value: values.reasonForReferral,
    multiline: true,
  });
  addLabeledField('Clinical summary', 'clinicalSummary', {
    value: values.clinicalSummary,
    multiline: true,
  });
  addLabeledField('Date', 'date', { value: values.date });

  // Signature area: never a real embedded signature by default. Draw a
  // printed line and label; only place an image if the physician configured
  // their own file and it exists on disk.
  y -= 10;
  const sigLineY = y;
  page.drawLine({
    start: { x: left, y: sigLineY },
    end: { x: left + 220, y: sigLineY },
    thickness: 1,
    color: rgb(0, 0, 0),
  });
  page.drawText('Physician signature (sign manually, or configure SIGNATURE_IMAGE_PATH)', {
    x: left,
    y: sigLineY - 12,
    size: 8,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  const sigPath = signatureImagePath || process.env.SIGNATURE_IMAGE_PATH;
  if (sigPath && fs.existsSync(sigPath)) {
    const bytes = fs.readFileSync(sigPath);
    const ext = path.extname(sigPath).toLowerCase();
    const image = ext === '.jpg' || ext === '.jpeg'
      ? await doc.embedJpg(bytes)
      : await doc.embedPng(bytes);
    const sigHeight = 40;
    const scale = sigHeight / image.height;
    page.drawImage(image, {
      x: left,
      y: sigLineY + 2,
      width: image.width * scale,
      height: sigHeight,
    });
  }

  const bytes = await doc.save();
  fs.writeFileSync(outputPath, bytes);
  return outputPath;
}

module.exports = { generateReferralLetter };

// --- CLI: `node generate.cjs [outputPath]` writes a sample with placeholder
// (clearly fake, non-PHI) values. ---
if (require.main === module) {
  try {
    require('dotenv').config({ path: path.join(__dirname, '..', '.env') });
  } catch (err) {
    // optional
  }
  const outputPath = process.argv[2] || path.join(__dirname, 'sample-referral.pdf');
  generateReferralLetter(outputPath, {
    fromPhysicianName: 'Dr. Example Physician',
    fromClinicName: 'Example Community Clinic',
    patientName: 'Jane Example',
    dateOfBirth: '1990-01-01',
    referredToProviderOrClinic: 'Example ENT Clinic',
    reasonForReferral: 'Sample referral -- replace with real clinical content before sending.',
    clinicalSummary: 'This is placeholder sample text generated by instanthpi/pdf/generate.cjs.',
    date: new Date().toISOString().slice(0, 10),
  })
    .then((p) => console.log(`Wrote sample referral letter to ${p}`))
    .catch((err) => {
      console.error(err.message);
      process.exitCode = 1;
    });
}
